name: lint

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**/*.gitattributes'
    - '**/*.gitignore'
    - '**/*.md'
  pull_request:
  workflow_dispatch:

permissions: {}

env:
  FORCE_COLOR: 3
  TERM: xterm

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0

    - name: Lint markdown
      uses: davidanson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
      with:
        config: '.markdownlint.json'
        globs: |
          **/*.md

    - name: dotnet Format
      run: dotnet format --verify-no-changes

